"""Put a hand-drawn sprite strip on the real screen, before it joins the frog.

A strip is a PNG of 64x64 cells side by side, transparent background, the frog in the
same place in every cell. Each cell goes on an 80x80 grid (the 64 cell centered) over a
background color, and the firmware scales that 3x to fill the 240x240 screen.

Run from the repo root, then flash the art-check build:
  python3 faces/art_check.py faces/art/content.png
  python3 faces/art_check.py faces/art/happy.png --bg happy --seq 0:200,1:200
  cd firmware && pio run -e artcheck -t upload

--seq is "cell:ms,cell:ms,..." in the order to play. Without it, a 5-cell strip plays
as an idle (hold, squash, stretch, hold, blink) and anything else shows each cell 400 ms.
--bg is a state name from frog.BG or a hex color. It also warns where a strip breaks
docs/sprite-brief.md (feet row, soft edges) and lists colors that content.png doesn't use.
"""
import argparse
import os
import sys

import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import frog  # noqa: E402

CELL = 64
N = 80  # screen grid: 240 / 3
OUT = os.path.join(HERE, "..", "firmware", "include", "art_check.h")
FEET_ROW = 61  # lowest frog pixel in every cell of content.png
REFERENCE = os.path.join(HERE, "art", "content.png")
IDLE5 = [(0, 1400), (3, 110), (4, 130), (0, 1400), (1, 60), (2, 110), (1, 60)]


def rgb565(r, g, b):
    return ((int(r) & 0xF8) << 8) | ((int(g) & 0xFC) << 3) | (int(b) >> 3)


def check(strip, ncells):
    """Warn where a strip breaks docs/sprite-brief.md, so the frog doesn't jump between faces."""
    px = np.array(strip)
    alpha = set(np.unique(px[..., 3]))
    if alpha - {0, 255}:
        print("warning: soft edges (alpha other than 0 or 255) will show as fringes on the background")
    for i in range(ncells):
        ys, xs = np.nonzero(px[:, i * CELL:(i + 1) * CELL, 3])
        if len(ys) and ys.max() != FEET_ROW:
            print(f"warning: cell {i} feet on row {ys.max()}, expected {FEET_ROW}: the frog will hop")
    ref = Image.open(REFERENCE).convert("RGBA")
    ref_colors = {p[:3] for p in ref.getdata() if p[3]}
    new = {tuple(p[:3]) for p in px.reshape(-1, 4) if p[3]} - ref_colors
    if new:
        print(f"note: {len(new)} colors not in content.png: " + " ".join("#%02X%02X%02X" % c for c in sorted(new)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("strip")
    ap.add_argument("--bg", default="content")
    ap.add_argument("--seq")
    a = ap.parse_args()

    strip = Image.open(a.strip).convert("RGBA")
    if strip.height != CELL or strip.width % CELL:
        sys.exit(f"{a.strip}: {strip.width}x{strip.height}, expected 64 tall and a multiple of 64 wide")
    ncells = strip.width // CELL
    bg = frog.hexc(frog.BG.get(a.bg, a.bg))

    if a.seq:
        seq = [tuple(int(v) for v in s.split(":")) for s in a.seq.split(",")]
    elif ncells == 5:
        seq = IDLE5
    else:
        seq = [(i, 400) for i in range(ncells)]
    if any(c >= ncells for c, _ in seq):
        sys.exit(f"--seq names a cell past the last one ({ncells - 1})")

    check(strip, ncells)
    off = (N - CELL) // 2
    imgs = []
    for i in range(ncells):
        canvas = Image.new("RGBA", (N, N), (*bg, 255))
        canvas.alpha_composite(strip.crop((i * CELL, 0, (i + 1) * CELL, CELL)), (off, off))
        imgs.append(np.array(canvas.convert("RGB")))
    colors = np.unique(np.concatenate([im.reshape(-1, 3) for im in imgs]), axis=0)
    if len(colors) > 256:
        sys.exit(f"{len(colors)} colors, more than one byte can index")
    lut = {tuple(c): i for i, c in enumerate(colors)}

    L = [
        f"// GENERATED by faces/art_check.py from {os.path.relpath(a.strip)}. Do not edit by hand.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "namespace art_check {",
        f"constexpr int kW = {N};",
        f"constexpr int kH = {N};",
        f"constexpr int kCells = {ncells};",
        f"constexpr int kSteps = {len(seq)};",
        "static const uint16_t kColors[] = {" + ", ".join(f"0x{rgb565(*c):04X}" for c in colors) + "};",
        "// {cell, ms} in play order.",
        "static const uint16_t kSeq[kSteps][2] = {" + ", ".join(f"{{{c}, {ms}}}" for c, ms in seq) + "};",
        "static const uint8_t kCellPx[kCells][kW * kH] = {",
    ]
    for im in imgs:
        px = [lut[tuple(p)] for p in im.reshape(-1, 3)]
        L.append("  {")
        for y in range(N):
            L.append("    " + ",".join(map(str, px[y * N:(y + 1) * N])) + ",")
        L.append("  },")
    L += ["};", "}  // namespace art_check", ""]
    with open(OUT, "w") as f:
        f.write("\n".join(L))
    print(f"{ncells} cells, {len(colors)} colors, {len(seq)} steps -> {os.path.relpath(OUT)}")


if __name__ == "__main__":
    main()
