"""Export the frog animations from frog.py into a C header the firmware can draw.

Each frame is stored at its native 60x60 size as one byte per pixel (an index into
a small color table); the firmware scales it 4x on the device. Every face (state)
gets a clip: its loop frames, how long each shows, and an optional blink frame.

Run from the repo root:  python3 faces/export_sprites.py
Re-run it any time frog.py changes, then rebuild the firmware.
"""
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import frog  # noqa: E402

OUT = os.path.join(HERE, "..", "firmware", "include", "sprites.h")


def rgb565(r, g, b):
    return ((int(r) & 0xF8) << 8) | ((int(g) & 0xFC) << 3) | (int(b) >> 3)


def main():
    palettes = list(frog.PALETTES)
    states = frog.STATES

    # Frame layout is the same for every palette: each state's loop frames, then its
    # blink frame if it has one.
    clips = []  # (first, count, blink_index or -1, [ms...])
    order = []  # (state, kind) where kind is a loop index or "blink"
    for s in states:
        loop = frog.ANIM[s]["frames"]
        first = len(order)
        order += [(s, i) for i in range(len(loop))]
        blink = -1
        if frog.ANIM[s]["blink"]:
            blink = len(order)
            order.append((s, "blink"))
        clips.append((first, len(loop), blink, [f["ms"] for f in loop]))

    tables, frames = [], []
    for pname in palettes:
        P = frog.PALETTES[pname]
        cache = {s: frog.frames(s, P) for s in states}
        imgs = [frog.blink_frame(s, P) if k == "blink" else cache[s][k][0] for s, k in order]
        colors = np.unique(np.concatenate([im.reshape(-1, 3) for im in imgs]), axis=0)
        if len(colors) > 256:
            sys.exit(f"{pname}: {len(colors)} colors, more than one byte can index")
        lut = {tuple(c): i for i, c in enumerate(colors)}
        tables.append([rgb565(*c) for c in colors])
        frames.append([[lut[tuple(px)] for px in im.reshape(-1, 3)] for im in imgs])
        print(f"{pname}: {len(colors)} colors")
    print(f"{len(order)} frames per palette, {len(order) * frog.N * frog.N * len(palettes) // 1024} KB")

    L = [
        "// GENERATED by faces/export_sprites.py from faces/frog.py. Do not edit by hand.",
        "#pragma once",
        "#include <stdint.h>",
        '#include "anim.h"',
        "",
        "namespace sprites {",
        f"constexpr int kW = {frog.N};",
        f"constexpr int kH = {frog.N};",
        "",
        "enum Palette : uint8_t { " + ", ".join(p.upper() for p in palettes) + ", PALETTE_COUNT };",
        "enum State : uint8_t { " + ", ".join(s.upper() for s in states) + ", STATE_COUNT };",
        "",
        f"constexpr int kFrameCount = {len(order)};",
    ]
    ncolors = max(len(t) for t in tables)
    L.append(f"constexpr int kColorCount = {ncolors};")
    L.append("")
    L.append("// How long each loop frame shows, in ms.")
    for s, (_, _, _, ms) in zip(states, clips):
        L.append(f"static const uint16_t kMs_{s}[] = {{{', '.join(map(str, ms))}}};")
    L.append("")
    L.append("// One clip per state: {first frame, frame count, blink frame or -1, durations}.")
    L.append("static const anim::Clip kClips[STATE_COUNT] = {")
    for s, (first, count, blink, _) in zip(states, clips):
        L.append(f"  {{{first}, {count}, {blink}, kMs_{s}}},  // {s}")
    L.append("};")
    L.append("")
    L.append("// RGB565 colors, one table per palette.")
    L.append("static const uint16_t kColors[PALETTE_COUNT][kColorCount] = {")
    for pname, t in zip(palettes, tables):
        t = t + [0] * (ncolors - len(t))
        L.append(f"  {{ // {pname}")
        for i in range(0, len(t), 12):
            L.append("    " + ", ".join(f"0x{c:04X}" for c in t[i:i + 12]) + ",")
        L.append("  },")
    L.append("};")
    L.append("")
    L.append("// Color-table index per pixel, row by row.")
    L.append("static const uint8_t kFrames[PALETTE_COUNT][kFrameCount][kW * kH] = {")
    for pname, fr in zip(palettes, frames):
        L.append(f"  {{ // {pname}")
        for (s, k), px in zip(order, fr):
            L.append(f"    {{ // {s} {k}")
            for y in range(frog.N):
                L.append("      " + ",".join(str(v) for v in px[y * frog.N:(y + 1) * frog.N]) + ",")
            L.append("    },")
        L.append("  },")
    L.append("};")
    L.append("}  // namespace sprites")
    L.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(L))
    print("wrote", os.path.relpath(OUT))


if __name__ == "__main__":
    main()
