"""Export the frog faces from frog.py into a C header the firmware can draw.

Each face is stored at its native 60x60 size as one byte per pixel (an index into
a small color table). The firmware scales it 4x on the device. That keeps all
18 faces (9 states x 2 palettes) to about 65 KB of flash, with no PNG decoding.

Run from the repo root:  python3 faces/export_sprites.py
Re-run it any time frog.py changes, then rebuild the firmware.
"""
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import frog  # noqa: E402

OUT = os.path.join(HERE, "..", "firmware", "include", "sprites.h")


def rgb565(r, g, b):
    return ((int(r) & 0xF8) << 8) | ((int(g) & 0xFC) << 3) | (int(b) >> 3)


def main():
    palettes = list(frog.PALETTES)  # ["mint", "lilac"]
    states = frog.STATES
    lines = [
        "// GENERATED by faces/export_sprites.py from faces/frog.py. Do not edit by hand.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "namespace sprites {",
        f"constexpr int kW = {frog.N};",
        f"constexpr int kH = {frog.N};",
        "",
        "enum Palette : uint8_t { " + ", ".join(p.upper() for p in palettes) + ", PALETTE_COUNT };",
        "enum State : uint8_t { " + ", ".join(s.upper() for s in states) + ", STATE_COUNT };",
        "",
    ]

    # One color table per palette, shared by all of that palette's faces.
    tables, frames = [], []
    for pname in palettes:
        imgs = [frog.scene(s, frog.PALETTES[pname]) for s in states]
        colors = np.unique(np.concatenate([im.reshape(-1, 3) for im in imgs]), axis=0)
        if len(colors) > 256:
            sys.exit(f"{pname}: {len(colors)} colors, more than one byte can index")
        lut = {tuple(c): i for i, c in enumerate(colors)}
        tables.append([rgb565(*c) for c in colors])
        frames.append([[lut[tuple(px)] for px in im.reshape(-1, 3)] for im in imgs])
        print(f"{pname}: {len(colors)} colors")

    ncolors = max(len(t) for t in tables)
    lines.append(f"constexpr int kColorCount = {ncolors};")
    lines.append("// RGB565 colors, one table per palette.")
    lines.append("static const uint16_t kColors[PALETTE_COUNT][kColorCount] = {")
    for pname, t in zip(palettes, tables):
        t = t + [0] * (ncolors - len(t))
        lines.append(f"  {{ // {pname}")
        for i in range(0, len(t), 12):
            lines.append("    " + ", ".join(f"0x{c:04X}" for c in t[i:i + 12]) + ",")
        lines.append("  },")
    lines.append("};")
    lines.append("")
    lines.append("// Color-table index per pixel, row by row.")
    lines.append("static const uint8_t kFrames[PALETTE_COUNT][STATE_COUNT][kW * kH] = {")
    for pname, fr in zip(palettes, frames):
        lines.append(f"  {{ // {pname}")
        for s, px in zip(states, fr):
            lines.append(f"    {{ // {s}")
            for y in range(frog.N):
                row = px[y * frog.N:(y + 1) * frog.N]
                lines.append("      " + ",".join(str(v) for v in row) + ",")
            lines.append("    },")
        lines.append("  },")
    lines.append("};")
    lines.append("}  // namespace sprites")
    lines.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print("wrote", os.path.relpath(OUT))


if __name__ == "__main__":
    main()
